# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: false
bioc_packages: limma
r_github_packages: 
  -  sneha-matrix/MAGMA 
env:
  - VDIFFR_RUN_TESTS=false
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
after_success:
  - Rscript -e 'covr::codecov()'
